### ISSUE TITLE
AUTOCONVERSION dla zakupu w walucie innej niż waluta rachunku Exante

### ISSUE THREAD

**Issue by rysiok** [PiotrZSL/BrokerReport#1]
Na wstępie wielkie dzięki za podzielenie się rozwiązaniem. Właśnie zasiadłem do tworzenia swojego, jednak jak zawsze w takich przypadkach, dobrze sprawdzić czy ktoś już nie wrzucił czegoś użytecznego do sieci.

W tej chwili jestem na początkowym etapie analizy Twojego rozwiązania więc nie będę jeszcze w stanie zaproponować poprawki. Zgłaszam problem.

Realizowałem transakcje na ZSIL.SIX. W logach mam konwersję z USD na CHF. W tej chwili tego typu transakcje nie są przetwarzane. Warunek na typ AUTOCONVERSION nie łapie tej transakcji, bo jej symbol nie jest pusty.

Załączam pliki.
[Financial_XXX.csv.txt](https://github.com/PiotrZSL/BrokerReport/files/6221930/Financial_XXX.csv.txt)
[Trades_XXX.csv.txt](https://github.com/PiotrZSL/BrokerReport/files/6221931/Trades_XXX.csv.txt)

W związku z rozbieżnością w kolumnach do swoich plików musiałem zmienić indeksy kolumn:
        C_TIME = 0
        C_COUNT = 8
        C_ISIN = 4
        C_SYMBOL = 3
        C_CURRENCY = 7
        C_TYPE = 4
        C_VOLUME = 12
        C_SIDE = 2
        C_COMMISSION = 9
        C_COMMISSION_CURRENCY = 10
        F_WHEN = 5
        F_SYMBOL = 2
        F_TYPE = 4
        F_ASSET = 7
        F_COMMENT = 9
        F_SUM = 6

Zamierzam przygotować kawałek kodu, który dynamicznie rozpoznaje, jakie kolumny na jakich pozycjach się znajdują.

**Comment by PiotrZSL** [comment]
Zmienił się format, faktycznie w Financial doszła kolumna ISIN.
Kolumny mam dlatego że w zależności czy wygeneruje raport w PL czy US to łapie.
Dawniej był nazwy.

**Comment by rysiok** [comment]
To faktycznie pomysł z dynamicznym rozpoznawaniem może być bardziej skomplikowany. Nie wziąłem pod uwagę, że może to zależeć od języka.

**Comment by rysiok** [comment]
Z tego co widzę to fix nie umożliwia zaciągnięcia transakcji z AUTOCONVERSION przy zakupie w innej walucie niż waluta rachunku. Czy masz gdzieś opisany algorytm, RE idzie opornie bez testów i komentarzy :-)?
Mogę pomóc.

**Comment by PiotrZSL** [comment]
Sprawdzam

**Comment by PiotrZSL** [comment]
Problem jest w tym że gdy robi się konwersje walut ręcznie (klikając auto-konwersje) to ładnie rekordy się ustawiają w parach.
Gdy auto-konwersja jest robiona automatycznie to się to przeplata niekiedy wewnątrz transakcji w raportach, do tego niekiedy w różnej kolejności. Przez co ciężko wychwycić co jest konwertowane na co.

Zaimplementowałem to dość prosto, i tak liczenie podatku jest zrobione w walucie oryginalnej.
Algorytmu opisanego nie mam, to po prostu wczytywanie wiersza po wierszu i próbowanie walidacji

**Comment by rysiok** [comment]
Posiedzę na tym, w tej chwili mogę to traktować jako próbkę testową. Mam tylko zakupy więc do liczenia podatku nie dojdzie, Jak będę miał poprawkę zrobię PR lub podrzucę diff'a.

**Comment by PiotrZSL** [comment]
Imo najprościej to przesortować rekordy autoconversion po dacie, symbolu, i abs(cena). Wtedy mappowanie powinno byc ok. Chodź w tym przypadku fajnie by było jakoś powiązać te auto-conversion z transakcją.

**Comment by rysiok** [comment]
Posiedzę na tym, w tej chwili moge to traktować jako próbkę testową. Mam tylko zakupy więc do liczenia podatku nie dojdzie :-)

**Comment by rysiok** [comment]
Potrzebuję trochę czasu by zobrazować sobie strukturę danych, na której działa algorytm.
